- DataWarrior/DataWarrior.download.recipe
- DataWarrior/DataWarrior.pkg.recipe
- GIMP/GIMP.pkg.recipe
- ISLLightClient/ISLLightClient.pkg.recipe
- LibreOffice/LibreOfficeLangPack.pkg.recipe
- LineIn/LineIn.download.recipe
- LineIn/LineIn.install.recipe
- eqMac/eqMac.download.recipe
- eqMac/eqMac.install.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
> Remove NAME variable from app paths

- AppleJava6/Java6Versioner.py
- CommonProcessors/ChangeModeOwner.py
- CommonProcessors/ChoicesXMLGenerator.py
- CommonProcessors/SubDirectoryList.py
- FileMaker/FilemakerProAdvancedUpdateExtractor.py
- FileMaker/FilemakerProAdvancedUpdateURLProcessor.py
- Parallels/ParallelsDesktopPackager.py
- PostProcessors/slacker.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later (including `urllib2.urlopen()` and `urllib2.urlparse()`), but this should catch the low-hanging fruit right now.
> Basic python3 compatibility

- AmazonCorrettoJDK/AmazonCorrettoJDK8.pkg.recipe
Replaced the Search url to https://github.com/corretto/corretto-8/releases/latest as the previous url no longer works.
> New SEARCH_URL

- GIMP/GIMP.pkg.recipe
- LibreOffice/LibreOfficeLangPack.pkg.recipe
- LogitechPresentation/LogitechPresentation.pkg.recipe
- MestReNova/MestReNova.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
> Adjust PkgCreator arguments

- CotEditor/CotEditor.pkg.recipe
- DataWarrior/DataWarrior.pkg.recipe
- Element/Element.pkg.recipe
- FileZilla/FileZilla-stable.download.recipe
- FileZilla/FileZilla-stable.pkg.recipe
- KNIME/KNIME.pkg.recipe
- Riot/Riot.pkg.recipe
- ThinLincClient/ThinLincClient.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
This PR also …
> Remove unused BUNDLE_ID input var and fix FileZilla regex

- AmazonCorrettoJDK/AmazonCorrettoJDK11.pkg.recipe
- updates AmazonCorrettoJDK11.pkg.recipe search path to use github releases when discovering latest version (CorrettoJDK8 recipe does this already)
- ran updated recipe, latest version of corretto11 was discovered and downloaded
```
Processing ./AmazonCorrettoJDK/AmazonCorrettoJDK11.pkg.recipe...
WARNING: ./AmazonCorrettoJDK/AmazonCorrettoJDK11.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (url): https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-macosx-x64.tar.gz
URLTextSearcher: Found matching text (match): https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-macosx-x64.tar.gz
URLDownloader
URLDownloader: Storing new …
```
> Update AmazonCorrettoJDK11 pkg recipe search url to use github releases

- JamfUploaderProcessors/READMEs/JamfPolicyDeleter.md
New text is copied from the processor (old text was for JamfPolicyUploader).
> Correct the description in JamfPolicyDeleter ReadMe

- JamfUploaderProcessors/JamfComputerProfileUploader.py
- JamfUploaderProcessors/JamfPolicyUploader.py
- Jamf_Package_Only_Recipes/Nudge-pkg-upload.jamf.recipe.yaml
- Jamf_Package_Only_Recipes/erase-install-pkg-upload.jamf.recipe.yaml
This PR adds `changed_policy_id` as an output variable for the JamfPolicyUploader processor.
This new output variable makes the policy object ID of a created or modified policy available for use in subsequent processors.
Example use cases:
1. Adding `jamf policy -id <changed_policy_id>` to the "Execute Command" payload of a subsequent policy, for instances where using a custom trigger (e.g. `jamf policy -event <customer trigger>`) is not feasible due to multiple policies using the same trigger.
2. Using the policy ID in the policy name of a subsequent policy. For example, your organization's naming scheme might prefer to note the ID of a chained policy in a Self Service description, etc.
If applicable, `changed_policy_id` is populated by *each run of JamfPolicyUploader*. For this reason, …
> Add `changed_policy_id` as a JamfPolicyUploader output variable

- JamfUploaderProcessors/JamfPackageUploader.py
- JamfUploaderProcessors/READMEs/JamfPackageUploader.md
As discussed in #89, but this also changes the input keys for the processor.
This PR fixes `JamfPackageUploader` not correctly setting a package's OS requirements due to an incorrectly named XML key.
This changes the uploaded XML key from `os_requirement` to `os_requirements`, as detailed in the [Jamf API documentation](https://developer.jamf.com/jamf-pro/reference/createpackagebyid). The processor itself has also been modified to only accept `os_requirements` as an input key, and the README for the processor has also been updated to reflect this.
I'm also opening a similar PR against https://github.com/grahampugh/jamf-upload with the same changes.
> Fixed os_requirements not being included correctly in pkg XML

- CommonProcessors/ChangeModeOwner.py
- CommonProcessors/PkgInfoReader.py
- CommonProcessors/Sleep.py
- CommonProcessors/StringReplacer.py
- Intellij/IntellijURLProvider.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
> Update Python path in processors to reflect changes in macOS 12.3+

- Jamf_Recipes/1Password.jamf.recipe
- changed `ParentRecipe` to com.github.nstrauss.pkg.1Password (this recipe has been updated to package the latest 1Password release, whereas the previous one was linked to a 1Password 7-specific recipe)
> changed ParentRecipe

- JamfUploaderProcessors/JamfPolicyLogFlusher.py
- JamfUploaderProcessors/READMEs/JamfPolicyLogFlusher.md
- In JamfPolicyLogFlusher.py, the input_variable description for policy_name incorrectly states that the policy will be deleted, not flushed.
- The ReadMe for JamfPolicyLogFlusher.py does not match the code (the policy_name descriptor is more accurate than the code but not particularly descriptive, and the interval does not match the code).
This PR fixes those documentation issues.
> Fix inconsistent/incorrect descriptions in JamfPolicyLogFlusher

- JamfUploaderProcessors/JamfExtensionAttributeUploader.py
- JamfUploaderProcessors/READMEs/JamfExtensionAttributeUploader.md
Moves the data_type value included in the ea_data object from a hard-coded value of "String" to an optional input_variable ea_data_type, which defaults to "String". Allows script Extension Attributes created with AutoPkg via JamfExtensionAttributeUploader to have data types other than String ie Integer or Date.
> Add ea_data_type optional input variable

- AppleJava6/Java6Versioner.py
- CommonProcessors/ChoicesXMLGenerator.py
- CommonProcessors/JSSRecipeReceiptChecker.py
- CommonProcessors/SMBMounter.py
- CommonProcessors/SMBUnmounter.py
- CommonProcessors/WritePkgResultToJson.py
- FileMakerProAdvanced/FilemakerProAdvancedUpdateExtractor.py
- JamfUploaderProcessors/CHANGELOG.md
- JamfUploaderProcessors/JamfExtensionAttributeUploader.py
- JamfUploaderProcessors/JamfPackageUploader.py
- JamfUploaderProcessors/JamfPolicyLogFlusher.py
- JamfUploaderProcessors/JamfUploaderLib/JamfUploaderBase.py
- JamfUploaderProcessors/READMEs/JamfExtensionAttributeUploader.md
- JamfUploaderProcessors/READMEs/JamfPackageUploader.md
- JamfUploaderProcessors/READMEs/JamfPolicyLogFlusher.md
- Parallels/ParallelsDesktopPackager.py
- PostProcessors/LastRecipeRunResult.py
- PostProcessors/slacker.py
- PreProcessors/LastRecipeRunChecker.py
Adds functionality for multiple SMB repos, plus the ability to specify both a Cloud Distribution Point and one or more SMB repos. These changes only affect `JamfPackageUploader`.
For details on how this works, see https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors#advanced-settings-for-distribution-points-coming-soon.
In short:
- If you are using Jamf Cloud with the JCDS: no change
- If you are on-premises, using a single SMB distribution point: no change
- If you have multiple SMB repos, you can now specify them in two alternative ways: 
- Either using multiple keys (`SMB_URL`, `SMB_USERNAME`, `SMB_PASSWORD`; `SMB2_URL`, `SMB2_USERNAME`, `SMB2_PASSWORD`; `SMB3_URL`; `SMB3_USERNAME`, `SMB3_PASSWORD`; etc.)
- Using an array  in the autopkg prefs (see wiki for …
> multirepo changes

- AmazonCorrettoJDK/AmazonCorrettoJDK11.pkg.recipe.yaml
This recipe is saving the Correto 11 package as `%RECIPE_CACHE_DIR%/AmazonCorettoJDK11-%version%.pkg`
(notice the missing r)
this is breaking our overrides that expect
```
<key>pkg_path</key>
<string>%RECIPE_CACHE_DIR%/AmazonCorettoJDK11-%version%.pkg</string>
```
Autopkg run output
```
MunkiImporter
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Users/victor_desouza/src/munki
MunkiImporter: File /Users/victor_desouza/Library/AutoPkg/Cache/local.munki.AmazonCorretto11/AmazonCorrettoJDK11-11.0.19.7.1.pkg does not exist
creating pkginfo for /Users/victor_desouza/Library/AutoPkg/Cache/local.munki.AmazonCorretto11/AmazonCorrettoJDK11-11.0.19.7.1.pkg failed: File /Users/victor_desouza/Library/AutoPkg/Cache/local.munki.AmazonCorr …
```
> Correct Correto 11 package name

- Nudge/Nudge.pkg.recipe.yaml
Made a change to the Nudge Pkg recipe to allow it to correctly process a pkg file for the Nudge_Suite. The parent download recipe allows for an INPUT variable specifying the type to download alternate pkgs from Github but this pkg recipe fails when using the "_Suite" type. I have added a FileFinder Processor to correct this issue. I believe this issue must have been discovered in the munki recipe "com.github.erikng.munki.Nudge" too so I actually just replicated the solution which was implemented there (link to commit below for reference).
https://github.com/autopkg/erikng-recipes/commit/be5a627361c6ab12a74de6e2b086d261e5276612
I also just fixed up a small typo in the description for this pkg recipe which was referring to the App "Unison" rather than "Nudge".
Have tested this recipe in my …
> Fixed Nudge pkg recipe for Nudge_Suite download

- CommonProcessors/ChoicesXMLGenerator.py
`installer -showChoicesXML` can potentially output to `stdout` text other than the manifest `plist`, which then causes `ChoicesXMLGenerator.py` to fail. This PR applies a simple regex to the output to only look at the text from `<?xml` to `</plist>` before attempting to parse it as a `plist`.
While working on a recipe for Avid Sibelius, I discovered that `installer -showChoicesXML` output additional text before the manifest plist. Unfortunately the current pkg is paywalled, and the non-paywalled v7.1.3 does not contain the issue, so instead I will describe my findings.
The output when `installer -showChoicesXML` is run directly on the package was:
```
% installer -showChoicesXML -pkg Install\ Sibelius.pkg
System language detected is: en
Cheking toward es failed
System language detected …
```
> ChoicesXMLGenerator.py Add regex filter to installer output

- JamfComplianceEditor/JamfComplianceEditor.download.recipe.yaml
This PR switches the download for Jamf Compliance Editor to be from [the new Github releases page](https://github.com/Jamf-Concepts/jamf-compliance-editor/releases). This fixes #142.
Tested with the pkg recipe as working.
> Fix download for JCE (fixes #142)

- Jamf_Package_Upload_Only_Recipes/Slack-pkg-upload.jamf.recipe
- Jamf_Package_Upload_Only_Recipes/VisualStudioCode-pkg-upload.jamf.recipe
- Jamf_Recipes/Slack.jamf.recipe
- Jamf_Recipes/VisualStudioCode.jamf.recipe
- VisualStudioCode/VisualStudioCode.install.recipe.yaml
The recipes in killahquam-recipes have been deprecated and will be removed soon. (See https://github.com/autopkg/killahquam-recipes/issues/28 for details.)
This pull request adjusts the parents for recipes that reference killahquam-recipes. The parents have been changed to actively maintained recipes in other repos.
> Update parents that reference killahquam-recipes

- DataWarrior/DataWarrior.download.recipe.yaml
- DataWarrior/DataWarrior.pkg.recipe.yaml
- Parallels/ParallelsDesktop.pkg.recipe.yaml
- TeX/BasicTeX.download.recipe.yaml
It's important to use HTTPS for downloading software whenever possible in order to avoid the possibility of person-in-the-middle attacks (like the one that affected the Sparkle update framework [in January 2016](https://vulnsec.com/2016/osx-apps-vulnerabilities/)).
For this pull request, I detected and changed to HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure exit codes of recipe run remains the same before/after the change.
This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso).
Thanks for considering!
> Update all available URLs from HTTP to HTTPS

- FileZilla/FileZilla-stable.download.recipe.yaml
This PR deprecates the FileZilla recipes in this repo, which are not sufficiently distinct from the ones in keeleysam-recipes to merit the extra maintenance effort. The included deprecation message points users to keeleysam-recipes for alternatives.
> Deprecate FileZilla recipes

- MestReNova/MestReNova.download.recipe.yaml
This PR deprecates the non-function MestReNova recipes in this repo and points users to working equivalents in the andrewvalentine-recipes repo.
> Deprecate MestReNova recipes

- FoldingAtHome/FoldingAtHome.download.recipe.yaml
This PR updates the download method for Folding@Home.
Verbose recipe run output:
```
% autopkg run -vvq 'FoldingAtHome/FoldingAtHome.download.recipe.yaml'
Processing FoldingAtHome/FoldingAtHome.download.recipe.yaml...
WARNING: FoldingAtHome/FoldingAtHome.download.recipe.yaml is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(?P<urlpath>macos-\\d+-universal/release/fah-client_(?P<version>[\\d\\.]+)_universal\\.pkg)',
'url': 'https://download.foldingathome.org/releases/public/fah-client/meta.json'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (urlpath): macos-12-universal/release/fah-client_8.3.18_universal.pkg
URLTextSearcher: …
```
> Fix Folding@Home recipes

- LibreOffice/LibreOfficeLangPack.download.recipe.yaml
The non-functional LibreOffice language pack recipes in this repo are redundant with the functional ones in the wycomo-recipes repo. This PR deprecates these recipes and points users to alternatives.
> Deprecate LibreOffice language pack recipes

- MunkiToolsCore/MunkiToolsCore.install.recipe.yaml
- _Deprecated_Recipes/JSSImporterBeta/JSSImporterBeta.download.recipe.yaml
- _Deprecated_Recipes/_JSS_Recipes/Element.jss.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/AdobeCCDAFromConsoleForJamfPro.jss-upload.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/AdobeLicensingToolkit.jss-upload.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/CotEditor.jss-upload.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/FileZilla-stable.jss-upload.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/MestReNova.jss-upload.recipe.yaml
- _Deprecated_Recipes/_JSS_Upload_Only_Recipes/Unison.jss-upload.recipe.yaml
[JSSImporter](https://github.com/jssimporter/JSSImporter) is no longer maintained. This pull request marks JSS type recipes as deprecated, and urges users to consider switching to equivalent [JamfUploader](https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors) recipes.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
> Deprecate JSS recipes

- CommonProcessors/PkgInfoReader.py
- Adds call to `os.path.getsize()` to get `installer_item_size` in bytes
- Adds output and description for `installer_item_size`
> Add pkginfo size output
